# configuration
language: java
cache:
    - apt
    - $HOME/.m2

# build matrix
jdk:
    - oraclejdk8

# run steps
install:

script:
    - cd textdb 
    - mvn test

after_success:
    - cd textdb
    - bash <(curl -s https://codecov.io/bash)
